apiVersion: apps/v1
kind: Deployment
metadata:
  name: example2-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: example2-app
  template:
    metadata:
      labels:
        app: example2-app
    spec:
      containers:
      - name: example-container
        image: nginx:latest
        ports:
        - containerPort: 80